services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  flask:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - neo4j
    command: >
      sh -c "
        until curl http://neo4j:7474 > /dev/null 2>&1;
        do echo '🔄 En attente de Neo4j...'; sleep 1;
        done;
        python run.py
      "
    
    volumes:
      - .:/app

volumes:
  neo4j_data:
